# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jibjib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
