# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jibjib', '0003_auto_20160507_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='vote',
        ),
        migrations.AddField(
            model_name='vote',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_answer', to='jibjib.Answer'),
        ),
        migrations.AddField(
            model_name='vote',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
