# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jibjib', '0005_auto_20160509_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
